# Generated by Django 5.2.4 on 2025-09-27 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
        ('pets', '0007_remove_pet_qr_code_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionpost',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='adoptionpost',
            name='owner_message',
            field=models.TextField(default='No message provided for old posts.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionpost',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_post', to='pets.pet'),
        ),
    ]
