# Generated by Django 5.2.4 on 2025-09-11 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0003_pet_pet_photo_alter_pet_pet_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacc_name', models.CharField(max_length=100)),
                ('vacc_date', models.DateField()),
                ('vacc_certificate', models.ImageField(blank=True, null=True, upload_to='vacc_certificates/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pets.pet')),
            ],
        ),
    ]
