# Generated by Django 5.2.4 on 2025-09-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='vacc_certificate',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
