# Generated by Django 5.2.4 on 2025-11-11 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushtoken',
            options={'verbose_name': 'Pushy Notification Token', 'verbose_name_plural': 'Pushy Notification Tokens'},
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='token',
            field=models.CharField(max_length=255, unique=True, verbose_name='Pushy Device Token'),
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='pushtoken',
            unique_together={('user', 'token')},
        ),
    ]
