# Generated by Django 5.2.4 on 2025-10-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionrequest',
            name='attached_file',
            field=models.CharField(blank=True, null=True),
        ),
    ]
