# Generated by Django 5.2.4 on 2025-10-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_interactionrequest_attached_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionrequest',
            name='owner_response_message',
            field=models.TextField(blank=True, help_text='الرسالة الاختيارية من المالك عند قبول أو رفض الطلب.', null=True, verbose_name='Owner Response Message'),
        ),
        migrations.AlterField(
            model_name='interactionrequest',
            name='attached_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
