# Generated by Django 5.2.4 on 2025-12-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_interactionrequest_owner_response_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionrequest',
            name='owner_response_message',
            field=models.TextField(blank=True, help_text='Owner Messsage', null=True, verbose_name='Owner Response Message'),
        ),
    ]
