"""
Django settings for PetCare project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
#from dotenv import load_dotenv
import dj_database_url
# 💥 إضافة Cloudinary
import cloudinary
import cloudinary_storage
#dummy
#wkjjsjszhhhulllllllllll
#llllll

# قم بتحميل متغيرات البيئة من ملف .en
#load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
#SECRET_KEY = 'django-insecure-#@_9_zq&eioto*vd(3-qn)ayvtrs@f3@9sbj7)08doegcyax4k'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG') == 'True'
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')
AUTH_USER_MODEL = 'account.User'

# Email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER",'rahaftest0@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD",'tyyu utct ggrx dipo')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_TIMEOUT = 5


SITE_DOMAIN = "https://petcare-q9j0.onrender.com"
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')

PUSHY_SECRET_KEY = '1a759a76745936483a737e84c8d735d8f10f3e40bc3ac68e38397c9169e0'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'account',
    'corsheaders',
    'pets',
    'adoption',
    'mating',
    'appointment',
    'vaccination',
    'django_filters',
    'storage',
    'rest_framework_nested',
    'mood',
    'alerts',
    'requests',
    'cloudinary',
    'cloudinary_storage',
    'activity',
    'reward_app',
    'notifications',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    "AUTH_TOKEN_CLASSES": ('rest_framework_simplejwt.tokens.AccessToken',),
}

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PetCare.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PetCare.wsgi.application'

# Database - This section has been updated to support Render and local development
# For production on Render, it will use dj_database_url from the environment
# ... (بقية الاستيرادات والكود) ...

# Database - This section has been updated to support Render and local development
# For production on Render, it will use dj_database_url from the environment
# 💥 ملاحظة: يجب أن يحتوي المتغير DATABASE_URL على رابط Neon الكامل
DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            # 💥 تم تغيير conn_max_age إلى 0.
            # هذا يفرض على Django إغلاق الاتصال بقاعدة البيانات بعد كل طلب،
            # وهو ضروري لقواعد بيانات Serverless مثل Neon لضمان عملها بشكل صحيح.
            conn_max_age=0 
        )
    }
else:
    # Use SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# ... (بقية الإعدادات) ...

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
# Local media storage for development
# NOTE: For Render's free plan, you must use a cloud storage solution like Cloudinary.
# This local setup will not persist files on Render's ephemeral servers.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ----------------------------------------------------------------------
# 🖼️ CLOUDINARY CONFIGURATION (إعدادات Cloudinary)
# ----------------------------------------------------------------------

# 💥 تعريف متغيرات البيئة
CLOUDINARY_CLOUD_NAME = os.environ.get('CLOUDINARY_CLOUD_NAME')
CLOUDINARY_API_KEY = os.environ.get('CLOUDINARY_API_KEY')
CLOUDINARY_API_SECRET = os.environ.get('CLOUDINARY_API_SECRET')

# إذا كنت تريد تعيين Cloudinary كواجهة تخزين افتراضية:
# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# ----------------------------------------------------------------------


# CORS
CORS_ALLOW_ALL_ORIGINS = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REWARD_PROFILE_COMPLETE_POINTS = 50
REWARD_ADOPTION_POINTS = 100
REWARD_MATING_POINTS = 80
REWARD_PROFILE_REQUIRED_FIELDS = ['phone','location','profile_picture']



