# Generated by Django 5.2.4 on 2025-10-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
    ]
