# Generated by Django 5.2.4 on 2025-10-29 07:54

from django.db import migrations
def create_initial_activities(apps, schema_editor):
    """
    الدالة المسؤولة عن إنشاء الأنشطة الأساسية بشكل آمن.
    """
    # الحصول على النموذج 'Activity' من الحالة التاريخية للترحيل
    Activity = apps.get_model('activities', 'Activity')
    
    initial_activities = [
        # (system_name, name_ar, points, is_repeatable)
        ('PROFILE_COMPLETE', 'Complete Profile', 50, False),
        ('ADOPT_PET', 'Adopt a Pet', 200, True),
        ('PET_MATING', 'Pet Mating', 100, True),
    ]
    
    # نستخدم schema_editor.connection.alias لتجاوز مشاكل الاتصال أحياناً
    with schema_editor.connection.cursor() as cursor:
        for system_name, name, points, repeatable in initial_activities:
            # نستخدم get_or_create لتجنب تكرار السجلات
            Activity.objects.get_or_create(
                system_name=system_name,
                defaults={
                    'name': name,
                    'points_value': points,
                    'is_repeatable': repeatable
                }
            )


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20251028_0326'),
    ]

    operations = [
    ]
