# Generated by Django 5.2.4 on 2025-10-08 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0007_remove_pet_qr_code_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('Mate', 'Mating Request'), ('Adoption', 'Adoption Request')], default='Adoption', max_length=10)),
                ('message', models.TextField(verbose_name='Request Message')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='request_attachments/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='pets.pet', verbose_name='Requested Pet')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests_as_owner', to=settings.AUTH_USER_MODEL, verbose_name='Receiver (Owner)')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Interaction Request',
                'verbose_name_plural': 'Interaction Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
