# Generated by Django 5.2.4 on 2025-10-04 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mating', '0001_initial'),
        ('pets', '0007_remove_pet_qr_code_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matingpost',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='matingpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matingpost',
            name='owner_message',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='matingpost',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mating_post', to='pets.pet', unique=True),
        ),
    ]
