# Generated by Django 5.2.4 on 2025-08-09 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(choices=[('أسود', 'أسود'), ('أبيض', 'أبيض'), ('بني', 'بني'), ('رمادي', 'رمادي'), ('ذهبي', 'ذهبي'), ('كريمي', 'كريمي'), ('أسمر', 'أسمر'), ('قرفة', 'قرفة'), ('أزرق', 'أزرق'), ('أحمر', 'أحمر')], max_length=50)),
                ('pet_color', models.CharField(max_length=50)),
                ('pet_gender', models.CharField(max_length=20)),
                ('pet_birthday', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
