# Generated by Django 5.2.4 on 2025-08-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_color',
            field=models.CharField(choices=[('أسود', 'أسود'), ('أبيض', 'أبيض'), ('بني', 'بني'), ('رمادي', 'رمادي'), ('ذهبي', 'ذهبي'), ('كريمي', 'كريمي'), ('أسمر', 'أسمر'), ('قرفة', 'قرفة'), ('أزرق', 'أزرق'), ('أحمر', 'أحمر'), ('White', 'White')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(max_length=50),
        ),
    ]
