# Generated by Django 5.2.4 on 2025-09-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_pet_color_alter_pet_pet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/pets'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Brown', 'Brown'), ('Grey', 'Grey'), ('Golden', 'Golden'), ('Tan', 'Tan'), ('Creamy', 'Creamy'), ('Cinamon', 'Cinamon'), ('Ginger', 'Ginger'), ('Silver', 'Silver')], max_length=50),
        ),
    ]
