# Generated by Django 5.2.4 on 2025-09-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_pet_photo_alter_pet_pet_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
