# Generated by Django 5.2.4 on 2025-09-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_pet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], max_length=50),
        ),
    ]
