# Generated by Django 5.2.4 on 2025-09-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pet_pet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
