# Generated by Django 5.2.4 on 2025-09-23 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_pet_qr_code_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='qr_code_url',
        ),
    ]
