# Generated by Django 5.2.4 on 2025-10-16 22:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_remove_pet_qr_code_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='qr_code_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='qr_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='qr_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
