# Generated by Django 5.2.4 on 2025-10-18 19:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_pet_qr_code_image_pet_qr_token_pet_qr_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='qr_code_image',
            field=models.URLField(default='jjj', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='qr_url',
            field=models.URLField(default='lll', max_length=500),
            preserve_default=False,
        ),
    ]
