# Generated by Django 5.2.4 on 2025-10-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_alter_pet_qr_code_image_alter_pet_qr_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='qr_code_image',
        ),
        migrations.AlterField(
            model_name='pet',
            name='qr_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='qr_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
