# Generated by Django 5.2.4 on 2025-11-01 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_once_only', models.BooleanField(default=False, help_text='Check this if the user should only be awarded points for this activity once (e.g., Profile completion).', verbose_name='Once Only Award')),
                ('name', models.CharField(max_length=255, verbose_name='Activity Name')),
                ('system_name', models.CharField(max_length=50, unique=True, verbose_name='System Key')),
                ('points_value', models.IntegerField(verbose_name='Points Value')),
                ('interaction_type', models.CharField(choices=[('EARN', 'Earning Points'), ('REDEEM', 'Redeem Points')], default='EARN', max_length=10, verbose_name='Interaction Type')),
            ],
            options={
                'verbose_name': 'Activity/Reward Definition',
                'verbose_name_plural': 'Activity/Reward Definitions',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.IntegerField(verbose_name='Points Awarded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Points Earning Log',
                'verbose_name_plural': 'Points Earning Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
