# Generated by Django 5.2.4 on 2025-10-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0003_alter_mood_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='notes',
        ),
    ]
