# Generated by Django 5.2.4 on 2025-10-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='description',
        ),
    ]
