# Generated by Django 5.2.4 on 2025-10-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_remove_reward_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
