# Generated by Django 5.2.4 on 2025-09-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
