# Generated by Django 5.2.4 on 2025-09-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('signup', 'Signup Verification'), ('reset_password', 'Reset Password'), ('email_change', 'Email Change')], default='signup', max_length=20),
        ),
    ]
