# Generated by Django 5.2.4 on 2025-09-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('signup', 'Signup Verification'), ('reset_password', 'Reset Password')], default='signup', max_length=20),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
