# Generated by Django 5.2.4 on 2025-09-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_create_superuser'),
        ('account', '0005_otp_otp_type_alter_otp_code'),
    ]

    operations = [
    ]
